install ansible
install aspell
install boot2docker
install cocot
install coreutils
install cowsay
install editorconfig
install emacs --with-gnutls --srgb --cocoa
install ffmpeg
install fping
install git
install git-flow
install gnu-sed
install gnupg
install go --cross-compile-common
install imagemagick
install lv
install mercurial
install mobile-shell
install nkf
install node
install p7zip
install phantomjs
install rbenv
install ruby-build
install sl
install ssh-copy-id
install terminal-notifier
install the_platinum_searcher
install the_silver_searcher
install tmux
install wget
install zsh-completions
